/// Create task use case with validation
library;

import 'package:persona_codex/core/error/failure.dart';

import '../entities/task.dart';
import '../repositories/task_repository.dart';

/// Use case for creating a new task with business validation
class CreateTaskUseCase {
  final TaskRepository _repository;

  CreateTaskUseCase(this._repository);

  /// Create a new task with validation
  ///
  /// Business Rules:
  /// - Title must not be empty
  /// - Title must be <= 255 characters
  /// - Due date cannot be in the past (if provided)
  /// - Description must be <= 2000 characters (if provided)
  Future<Task> call(CreateTaskParams params) async {
    // Validation
    _validateParams(params);

    // Create task entity
    final task = Task(
      id: null, // Will be generated by Supabase
      title: params.title.trim(),
      description: params.description?.trim(),
      status: params.status,
      priority: params.priority,
      dueDate: params.dueDate,
      tags: params.tags,
      projectId: params.projectId,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      completedAt: null,
      isMoneyRelated: params.isMoneyRelated,
      expectedAmount: params.expectedAmount,
      transactionType: params.transactionType,
      financeCategoryId: params.financeCategoryId,
    );

    return await _repository.createTask(task);
  }

  void _validateParams(CreateTaskParams params) {
    // Title validation
    if (params.title.trim().isEmpty) {
      throw ValidationFailure('Task title cannot be empty');
    }

    if (params.title.length > 255) {
      throw ValidationFailure('Task title cannot exceed 255 characters');
    }

    // Due date validation
    if (params.dueDate != null) {
      final now = DateTime.now();
      final today = DateTime(now.year, now.month, now.day);
      final dueDay = DateTime(
        params.dueDate!.year,
        params.dueDate!.month,
        params.dueDate!.day,
      );

      if (dueDay.isBefore(today)) {
        throw ValidationFailure('Due date cannot be in the past');
      }
    }

    // Description validation
    if (params.description != null && params.description!.length > 2000) {
      throw ValidationFailure('Description cannot exceed 2000 characters');
    }

    // Tags validation
    if (params.tags.length > 10) {
      throw ValidationFailure('Cannot have more than 10 tags');
    }

    for (final tag in params.tags) {
      if (tag.trim().isEmpty) {
        throw ValidationFailure('Tags cannot be empty');
      }
      if (tag.length > 50) {
        throw ValidationFailure('Each tag must be <= 50 characters');
      }
    }
  }
}

/// Parameters for creating a task
class CreateTaskParams {
  final String title;
  final String? description;
  final TaskStatus status;
  final TaskPriority priority;
  final DateTime? dueDate;
  final List<String> tags;
  final String? projectId;
  final bool isMoneyRelated;
  final double? expectedAmount;
  final TaskTransactionType? transactionType;
  final String? financeCategoryId;

  CreateTaskParams({
    required this.title,
    this.description,
    this.status = TaskStatus.todo,
    this.priority = TaskPriority.medium,
    this.dueDate,
    this.tags = const [],
    this.projectId,
    this.isMoneyRelated = false,
    this.expectedAmount,
    this.transactionType,
    this.financeCategoryId,
  });
}
